import React,{useEffect,useState} from 'react'
import NavbarAdmin from './NavbarAdmin'
import {apiGet,apiPut,apiPatch,apiUpload} from './api'
import './MobileStudio.css'
export default function MobileStudio(){
 const [config,setConfig]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[page,setPage]=useState('men'),[layers,setLayers]=useState(['','','','']),[loadedPage,setLoadedPage]=useState(''),[sizeText,setSizeText]=useState('')
 useEffect(()=>{apiGet('/mobile/store').then(c=>{setConfig(c);setSizeText(c.customizer.sizes.join(', '))}).catch(e=>setError(e.message))},[])
 useEffect(()=>{let active=true;setLoadedPage('');setLayers(['','','','']);apiGet('/homepage-images',{page,section:'editorial'}).then(rows=>{if(active){setLayers(rows[0]?.extra?.layers||['','','','']);setLoadedPage(page)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[page])
 const edit=(i,k,v)=>setConfig(c=>({...c,customizer:{...c.customizer,garments:c.customizer.garments.map((g,j)=>i===j?{...g,[k]:v}:g)}}))
 async function run(fn,success){setBusy(true);setError('');setMessage('');try{await fn();setMessage(success)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function upload(file,index){if(!file)return;await run(async()=>{const data=new FormData();data.append('image',file);data.append('page',page);data.append('section','editorial-layer');data.append('slotOrder',String(index));const image=await apiUpload(`/homepage-images/mobile-${page}-layer-${index}/replace`,data);setLayers(v=>v.map((url,i)=>i===index?image.imageUrl:url))},'Layer uploaded. Save the scene to publish all four layers together.')}
 return <><NavbarAdmin/><main className="v1-studio"><h1>Store design studio</h1><p>The app uses the same catalogue, customers and orders as the website. Change website banners in Homepage Images. These controls manage custom clothing and shared website and mobile motion artwork.</p>{error&&<p role="alert" className="v1-studio-error">{error}</p>}{message&&<p role="status">{message}</p>}{!config?<button onClick={()=>run(async()=>{const c=await apiGet('/mobile/store');setConfig(c);setSizeText(c.customizer.sizes.join(', '))},'Settings loaded')}>Reload settings</button>:<section><h2>Custom clothing</h2><label><input type="checkbox" checked={config.customizer.enabled} onChange={e=>setConfig(c=>({...c,customizer:{...c.customizer,enabled:e.target.checked}}))}/> Enable design studio</label><div className="v1-studio-grid">{config.customizer.garments.map((g,i)=><fieldset key={g.id}><legend>{g.name}</legend><label><input type="checkbox" checked={g.enabled} onChange={e=>edit(i,'enabled',e.target.checked)}/> Available</label><label>Name<input value={g.name} onChange={e=>edit(i,'name',e.target.value)}/></label><label>Selling price (₹)<input type="number" min="1" step="0.01" value={g.price} onChange={e=>edit(i,'price',Number(e.target.value))}/></label><label>Original price (₹)<input type="number" min="1" step="0.01" value={g.mrp} onChange={e=>edit(i,'mrp',Number(e.target.value))}/></label></fieldset>)}</div><label>Support email<input type="email" value={config.support?.email||''} onChange={e=>setConfig(c=>({...c,support:{email:e.target.value}}))}/></label><label>Available sizes, separated by commas<input value={sizeText} onChange={e=>setSizeText(e.target.value)}/></label><button disabled={busy} onClick={()=>run(async()=>setConfig(await apiPut('/mobile/admin/store',{...config,customizer:{...config.customizer,sizes:sizeText.split(',').map(s=>s.trim()).filter(Boolean)}})),'Custom clothing settings saved. Checkout uses these prices.')}>{busy?'Saving…':'Save clothing settings'}</button></section>}
 <section><h2>Exploded collection scenes</h2><p>Upload four separate transparent clothing cutouts. The website and mobile app read these same layers. Save the scene to publish the images to both. Only clothing belongs in these scenes.</p><label>Collection<select disabled={busy} value={page} onChange={e=>setPage(e.target.value)}>{['men','women','kids'].map(p=><option key={p}>{p}</option>)}</select></label><div className="v1-studio-grid">{layers.map((url,i)=><fieldset key={i}><legend>Layer {i+1}</legend>{url&&<img src={url} alt={`Clothing layer ${i+1}`}/>}<label>Transparent image<input type="file" accept="image/png,image/webp" disabled={busy||loadedPage!==page} onChange={e=>upload(e.target.files?.[0],i)}/></label></fieldset>)}</div><button disabled={busy||loadedPage!==page||layers.some(x=>!x)} onClick={()=>run(()=>apiPatch(`/homepage-images/mobile-${page}-editorial`,{page,section:'editorial',slotOrder:0,altText:`${page} clothing inspiration`,extra:{layers}}),'Collection scene saved. Active apps refresh within about 15 seconds.')}>Save all four layers</button><button disabled={busy||loadedPage!==page} onClick={()=>run(async()=>{await apiPatch(`/homepage-images/mobile-${page}-editorial`,{page,section:'editorial',extra:{layers:[]}});setLayers(['','','',''])},'Bundled V1 artwork restored.')}>Restore original artwork</button></section><section><h2>Return policy</h2><p>7 days from confirmed delivery. Innerwear cannot be returned. Mixed orders permit eligible items only. These rules are enforced by the backend.</p></section></main></>
}
