import React, { useCallback, useEffect, useRef, useState } from 'react';
import './OrderOperations.css';
const defaultBase='https://vandhana-shopping-mall-backend.vercel.app';
export const API_BASE=(process.env.REACT_APP_API_BASE || defaultBase).replace(/\/+$/,'');
export const getStaffToken=()=>localStorage.getItem('auth_token')||localStorage.getItem('admin_token')||localStorage.getItem('token')||localStorage.getItem('adminToken')||localStorage.getItem('accessToken')||'';
export async function staffRequest(path,body,signal) {
  const response=await fetch(`${API_BASE}/api${path}`,{method:body===undefined?'GET':'POST',cache:'no-store',signal,
    headers:{'Content-Type':'application/json',Authorization:`Bearer ${getStaffToken()}`},body:body===undefined?undefined:JSON.stringify(body)});
  const data=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(response.status===401?'Please sign in again.':response.status>=500?'The server could not complete this request. Refresh and retry.':data.message||'Request could not be completed.');
  return data;
}
const cash=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(value||0));
const when=value=>value?new Date(value).toLocaleString('en-IN'):'Not recorded';
const label=value=>String(value||'Not recorded').replace(/_/g,' ');
function Badge({value}) {return <span className={`v1ops-badge ${/FAILED|REVIEW|RTO|CANCEL|REJECT/i.test(value)?'v1ops-red':/PENDING|REQUEST|APPROVE/i.test(value)?'v1ops-amber':'v1ops-green'}`}>{label(value)}</span>;}
function Entry({name,children}) {return <div className="v1ops-entry"><span>{name}</span><strong>{children}</strong></div>;}
function trapFocus(event){if(event.key!=='Tab')return;const nodes=[...event.currentTarget.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')].filter(node=>node.offsetParent!==null);const first=nodes[0],last=nodes[nodes.length-1];if(!first)return;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
function ActionDialog({action,busy,onClose,onSubmit}) {
  const [reason,setReason]=useState(''),[reference,setReference]=useState(''),[restock,setRestock]=useState(false),[confirmed,setConfirmed]=useState(false);
  const [parcel,setParcel]=useState({weight:'0.5',length:'10',breadth:'10',height:'5'});
  const ref=useRef(null);
  useEffect(()=>{ref.current?.focus();},[]);
  const monetary=action.type==='refund',manual=monetary && action.method==='COD' && Number(action.amount)>0;
  const reasonRequired=['cancel','rejectCancellation','rejectReturn','receive'].includes(action.type);
  const ready=(!reasonRequired||reason.trim().length>=5)&&(!monetary||confirmed)&&(!manual||reference.trim().length>=6)&&(action.type!=='approveReturn'||Object.values(parcel).every(v=>Number(v)>0));
  return <div className="v1ops-overlay v1ops-confirm" onClick={busy?undefined:onClose}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={action.title} className="v1ops-modal" onClick={e=>e.stopPropagation()} onKeyDown={e=>{trapFocus(e);if(e.key==='Escape'&&!busy)onClose();}}>
    <h2>{action.title}</h2><p>{action.description}</p>
    {monetary&&<><Entry name="Product cash refund">{cash(Number(action.amount)/100)}</Entry><Entry name="Reward points">{action.points||0}</Entry><p className="v1ops-muted">Delivery and COD fees are excluded. Online refunds go back to the original payment method. Points retain their original expiry.</p></>}
    {reasonRequired&&<label>{action.type==='receive'?'Inspection notes':'Reason'}<textarea value={reason} maxLength={1000} rows={3} onChange={e=>setReason(e.target.value)}/></label>}
    {action.type==='receive'&&<label className="v1ops-check"><input type="checkbox" checked={restock} onChange={e=>setRestock(e.target.checked)}/>Inspected items are sellable. Restore them to branch stock.</label>}
    {action.type==='approveReturn'&&<><p>Confirm the measured packed return parcel before booking. Choose the reverse courier and request pickup after approval.</p><div className="v1ops-parcel">{Object.keys(parcel).map(key=><label key={key}>{key==='weight'?'Weight (kg)':`${key} (cm)`}<input required type="number" min="0.01" step="0.01" value={parcel[key]} onChange={e=>setParcel(p=>({...p,[key]:e.target.value}))}/></label>)}</div></>}
    {manual&&<><label>Completed bank or UPI transfer reference<input value={reference} onChange={e=>setReference(e.target.value)} maxLength={100}/></label><p>Send this exact amount to the customer before recording the transfer. This form records the transfer and does not send money.</p></>}
    {monetary&&<label className="v1ops-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{manual?'I have sent the exact cash refund and verified its transfer reference.':'I confirm this exact refund amount and want to initiate it.'}</label>}
    <div className="v1ops-actions"><button disabled={busy} onClick={onClose}>Back</button><button className="v1ops-primary" disabled={busy||!ready} onClick={()=>onSubmit({reason,reference,restock,parcel,inspection_notes:reason,amount_paise:Number(action.amount||0),transfer_confirmed:confirmed,items_received:true})}>{busy?'Processing...':'Confirm'}</button></div>
  </section></div>;
}
function ShippingControls({id,onChanged}) {
  const [state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[remote,setRemote]=useState(''),[absent,setAbsent]=useState(false);
  const [parcel,setParcel]=useState({weight:'',length:'',breadth:'',height:''});
  const [couriers,setCouriers]=useState([]),[courier,setCourier]=useState(''),[pickups,setPickups]=useState([]),[pickup,setPickup]=useState('');
  const refresh=useCallback(async()=>{try{setState(await staffRequest(`/order-shipping/${id}`));setError('');}catch(e){setError(e.message);}},[id]);
  useEffect(()=>{void refresh();},[refresh]);
  async function run(path,body){if(busy)return;setBusy(true);setError('');try{const result=await staffRequest(`/order-shipping/${id}${path}`,body);if(path==='/couriers')setCouriers(result.couriers||result.available_courier_companies||result.data?.available_courier_companies||[]);else if(path==='/pickups')setPickups(result.pickups||[]);else{await refresh();await onChanged();}}catch(e){setError(e.message);}finally{setBusy(false);}}
  const closed=!!state?.blocked || (state?.sale && (/CANCEL|RETURN|RTO|DELIVER/.test(state.sale.status)||(state.sale.payment_method==='ONLINE'&&state.sale.payment_status!=='PAID')));
  return <section className="v1ops-card"><h3>Shiprocket dispatch</h3>{error&&<p role="alert" className="v1ops-error">{error}</p>}{state?.workflow?.last_error&&<p className="v1ops-error">{state.workflow.last_error}</p>}
    <Entry name="Shipping phase">{label(state?.workflow?.phase)}</Entry><Entry name="Carrier order ID">{state?.shipment?.shiprocket_order_id||'Not linked'}</Entry>
    {state?.blocked&&<p className="v1ops-muted">{state.blocked}</p>}
    <p className="v1ops-muted">Link an existing carrier booking first. A saved uncertain booking is never recreated automatically.</p>
    {!state?.shipment&&!closed&&<><label>Existing Shiprocket order ID<input value={remote} onChange={e=>setRemote(e.target.value.replace(/\D/g,''))} placeholder="Numeric carrier ID"/></label><label className="v1ops-check"><input type="checkbox" checked={absent} onChange={e=>setAbsent(e.target.checked)}/>I searched Shiprocket and confirmed this order has no booking.</label>{!remote&&<><p>Enter the measured packed parcel before creating a shipment.</p><div className="v1ops-parcel">{Object.keys(parcel).map(key=><label key={key}>{key==='weight'?'Dispatch weight (kg)':`Dispatch ${key} (cm)`}<input type="number" min="0.01" step="0.01" value={parcel[key]} onChange={e=>setParcel(p=>({...p,[key]:e.target.value}))}/></label>)}</div></>}<button disabled={busy||(!remote&&(!absent||!Object.values(parcel).every(v=>Number(v)>0)))} onClick={()=>void run('/connect',{remote_order_id:remote||undefined,confirmed_absent:absent,parcel:remote?undefined:parcel})}>{remote?'Link existing booking':'Create verified missing booking'}</button>
    <button disabled={busy} onClick={()=>void run('/pickups')}>Load pickup locations</button>{!!pickups.length&&<div className="v1ops-actions"><select aria-label="Pickup location" value={pickup} onChange={e=>setPickup(e.target.value)}><option value="">Choose a pickup</option>{pickups.map(p=><option key={p.id||p.pickup_id} value={p.id||p.pickup_id}>{p.pickup_location} ({p.pin_code})</option>)}</select><button disabled={busy||!pickup} onClick={()=>void run('/warehouse',{pickup_id:pickup})}>Map pickup</button></div>}</>}
    {state?.shipment&&!closed&&<><button disabled={busy} onClick={()=>void run('/couriers')}>Check available couriers</button>{!!couriers.length&&<div className="v1ops-actions"><select aria-label="Courier" value={courier} onChange={e=>setCourier(e.target.value)}><option value="">Choose courier</option>{couriers.map(item=><option key={item.courier_company_id} value={item.courier_company_id}>{item.courier_name} · {cash(item.rate)}</option>)}</select><button disabled={busy||!courier} onClick={()=>void run('/awb',{courier_id:Number(courier)})}>Generate AWB</button></div>}<button disabled={busy||!state.shipment.awb} onClick={()=>void run('/pickup',{})}>Request pickup</button></>}
    <div className="v1ops-actions"><button disabled={busy} onClick={()=>void run('/tracking')}>Refresh carrier status</button>{['label','invoice','manifest'].map(type=><button key={type} disabled={busy||!state?.shipment?.awb} onClick={async()=>{setBusy(true);try{const result=await staffRequest(`/order-shipping/${id}/documents/${type}`,{});const url=result.url||result[`${type}_url`];if(!/^https:\/\//.test(url||''))throw new Error('Document URL is unavailable.');window.open(url,'_blank','noopener,noreferrer');}catch(e){setError(e.message);}finally{setBusy(false);}}}>Open {type}</button>)}</div>
  </section>;
}
function ReverseControls({request,onChanged}) {
  const [couriers,setCouriers]=useState([]),[courier,setCourier]=useState(''),[remote,setRemote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function run(action,body){if(busy)return;setBusy(true);setError('');try{const result=await staffRequest(`/returns/${request.id}/shipping/${action}`,body);if(action==='couriers')setCouriers(result.couriers||[]);else await onChanged();}catch(e){setError(e.message);}finally{setBusy(false);}}
  if(request.items_received_at||['REJECTED','CANCELLED'].includes(request.status))return null;
  const reverse=request.reverse_shipment;
  return <div className="v1ops-reverse"><h4>Return courier</h4>{error&&<p className="v1ops-error" role="alert">{error}</p>}{reverse?.last_error&&<p className="v1ops-error">{reverse.last_error}</p>}
    {!reverse&&<><p className="v1ops-muted">For a booking timeout, find return reference RET-{request.id} in Shiprocket and link its numeric carrier order ID.</p><div className="v1ops-actions"><input aria-label="Shiprocket return order ID" value={remote} onChange={e=>setRemote(e.target.value.replace(/\D/g,''))} placeholder="Existing carrier return order ID"/><button disabled={busy||!remote} onClick={()=>void run('reconcile',{order_id:remote})}>Link return booking</button></div></>}
    {reverse&&<><p>{reverse.awb||'AWB pending'} · {label(reverse.status)}</p><button disabled={busy} onClick={()=>void run('reconcile',{})}>Refresh return carrier status</button>{request.status==='APPROVED'&&!reverse.awb&&<><button disabled={busy} onClick={()=>void run('couriers')}>Load reverse couriers</button>{!!couriers.length&&<div className="v1ops-actions"><select aria-label="Return courier" value={courier} onChange={e=>setCourier(e.target.value)}><option value="">Choose reverse courier</option>{couriers.map(item=><option key={item.courier_company_id} value={item.courier_company_id}>{item.courier_name} · {cash(item.rate)}</option>)}</select><button disabled={busy||!courier} onClick={()=>void run('awb',{courier_id:Number(courier)})}>Generate return AWB</button></div>}</>}{request.status==='APPROVED'&&reverse.awb&&<button disabled={busy||!!reverse.pickup_requested_at} onClick={()=>void run('pickup',{})}>{reverse.pickup_requested_at?'Return pickup recorded':'Request return pickup'}</button>}</>}
  </div>;
}
export default function OrderOperations() {
  const [filters,setFilters]=useState({queue:'',status:'ALL',q:'',payment_method:'',page:1}),[search,setSearch]=useState(''),[refresh,setRefresh]=useState(0);
  const [list,setList]=useState({rows:[],total:0,pages:0,page:1}),[summary,setSummary]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[detailError,setDetailError]=useState(''),[action,setAction]=useState(null),[busy,setBusy]=useState(false);
  const working=useRef(false), drawer=useRef(null);
  useEffect(()=>{if(!selected)return;const overflow=document.body.style.overflow;const previous=document.activeElement;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;if(previous?.isConnected)previous.focus();};},[selected]);
  useEffect(()=>{const timer=setTimeout(()=>setFilters(f=>({...f,q:search,page:1})),300);return()=>clearTimeout(timer);},[search]);
  useEffect(()=>{
    const controller=new AbortController();setLoading(true);
    const params=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==''));
    Promise.all([staffRequest(`/order-management/orders?${params}`,undefined,controller.signal),staffRequest('/order-management/summary',undefined,controller.signal)])
      .then(([orders,totals])=>{setList(orders);setSummary(totals);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    return()=>controller.abort();
  },[filters,refresh]);
  const loadDetail=useCallback(async()=>{if(selected){const result=await staffRequest(`/order-management/orders/${selected}`);setDetail(result);}},[selected]);
  useEffect(()=>{if(!selected){setDetail(null);return;}const controller=new AbortController();setDetail(null);setDetailError('');
    staffRequest(`/order-management/orders/${selected}`,undefined,controller.signal).then(setDetail).catch(e=>{if(!controller.signal.aborted)setDetailError(e.message);});
    drawer.current?.focus();return()=>controller.abort();},[selected]);
  useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!working.current){setRefresh(n=>n+1);if(selected)void loadDetail().catch(e=>setDetailError(e.message));}},30000);return()=>clearInterval(timer);},[selected,loadDetail]);
  async function run(path,body,done='Update saved.') {if(working.current)return;working.current=true;setBusy(true);setDetailError('');setMessage('');try{await staffRequest(path,body);setAction(null);await loadDetail();setRefresh(n=>n+1);setMessage(done);}catch(e){setDetailError(e.message);setAction(null);}finally{working.current=false;setBusy(false);}}
  function refund(kind,request) {setAction({type:'refund',title:`Refund ${kind==='RETURN'?'returned products':'cancelled order'}`,description:`Order ${selected}. Confirm the approved product amount.`,kind,id:kind==='RETURN'?request.id:selected,amount:request.refund_amount_paise,points:request.refund_points,method:detail.payment_method});}
  function submit(body){const a=action;let path;
    if(a.type==='refund')path=a.method==='COD'&&Number(a.amount)>0?(a.kind==='RETURN'?`/returns/${a.id}/refund-complete`:`/storefront/admin/cancellations/${a.id}/refund-complete`):`/order-management/refunds/${a.kind}/${a.id}/initiate`;
    else if(a.type==='cancel'){
      path='/orders/cancel';
      body={...body,sale_id:selected};
    }
    else if(a.type==='rejectCancellation')path=`/storefront/admin/cancellations/${selected}/reject`;
    else if(a.type==='approveReturn')path=`/returns/${a.id}/approve`;
    else if(a.type==='rejectReturn')path=`/returns/${a.id}/reject`;
    else if(a.type==='receive')path=`/order-management/returns/${a.id}/receive`;
    void run(path,body,a.type==='refund'?'Refund request recorded. Check its provider status for completion.':'Order update saved.');
  }
  const setFilter=(key,value)=>setFilters(f=>({...f,[key]:value,page:1}));
  const cancellation=detail?.cancellation;
  return <main className="v1ops"><header className="v1ops-header"><div><p className="v1ops-kicker">V1GARMENTS · STORE OPERATIONS</p><h1>Orders, from start to finish.</h1><p>Review dispatch, cancellations, returns and refunds in one place.</p></div><button disabled={loading||busy} onClick={()=>{setRefresh(n=>n+1);if(selected)void loadDetail().catch(e=>setDetailError(e.message));}}>Refresh</button></header>
    <div className="v1ops-summary">{[['orders','All orders',''],['cancellation_requests','Cancellation requests','cancellations'],['return_requests','Returns to review','returns'],['refunds_pending','Refunds pending','refunds'],['exceptions','Needs attention','exceptions']].map(([key,title,queue])=><button key={key} className={filters.queue===queue?'v1ops-selected':''} onClick={()=>setFilter('queue',queue)}><span>{title}</span><strong>{summary[key]??'...'}</strong></button>)}</div>
    {message&&<p role="status" className="v1ops-note">{message}</p>}{error&&<p role="alert" className="v1ops-error">{error}</p>}
    <section className="v1ops-card"><div className="v1ops-filters"><label>Search orders<input placeholder="Order ID, customer, mobile or AWB" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Order status<select value={filters.status} onChange={e=>setFilter('status',e.target.value)}>{['ALL','PLACED','CONFIRMED','PACKED','SHIPPED','DELIVERED','CANCELLED','RTO'].map(v=><option key={v}>{v}</option>)}</select></label><label>Payment method<select value={filters.payment_method} onChange={e=>setFilter('payment_method',e.target.value)}><option value="">All methods</option><option>ONLINE</option><option>COD</option></select></label><label>Work queue<select value={filters.queue} onChange={e=>setFilter('queue',e.target.value)}><option value="">All orders</option><option value="cancellations">Cancellation requests</option><option value="returns">Returns to review</option><option value="refunds">Refunds pending</option><option value="exceptions">Needs attention</option></select></label></div>
      <div className="v1ops-table-scroll"><table><thead><tr><th>Order & customer</th><th>Order status</th><th>Payment</th><th>Courier</th><th>Cancellation / return</th><th>Total</th><th>Action</th></tr></thead><tbody>{list.rows.map(order=><tr key={order.id}><td><strong>#{order.id.slice(0,8).toUpperCase()}</strong><span>{order.customer_name||'Customer'}</span><small>{order.customer_mobile} · {when(order.created_at)}</small></td><td><Badge value={order.display_status||order.status}/></td><td><strong>{order.payment_method}</strong><span>{label(order.payment_status)}</span></td><td><span>{order.carrier_status||'Awaiting dispatch'}</span><small>{order.awb||'No AWB yet'}</small></td><td>{order.cancellation_status?<><Badge value={order.cancellation_status}/><small>{order.cancellation_reason}</small></>:<small>{order.return_count||0} return requests</small>}{order.cancellation_refund_status&&<small>Refund: {label(order.cancellation_refund_status)}</small>}</td><td>{cash(order.total)}</td><td><button onClick={()=>setSelected(order.id)}>Review order</button></td></tr>)}</tbody></table></div>
      {loading&&<p role="status">Refreshing orders...</p>}{!loading&&!list.rows.length&&<p className="v1ops-empty">No orders match these filters.</p>}
      <footer className="v1ops-pagination"><span>{list.total} orders · Page {filters.page} of {Math.max(1,list.pages)}</span><button disabled={filters.page<=1||loading} onClick={()=>setFilters(f=>({...f,page:f.page-1}))}>Previous</button><button disabled={filters.page>=list.pages||loading} onClick={()=>setFilters(f=>({...f,page:f.page+1}))}>Next</button></footer>
    </section>
    {selected&&<div className="v1ops-overlay" onClick={()=>{if(!busy&&!action)setSelected(null);}}><section ref={drawer} tabIndex={-1} className="v1ops-drawer" role="dialog" aria-modal="true" aria-label="Order review" onClick={e=>e.stopPropagation()} onKeyDown={e=>{trapFocus(e);if(e.key==='Escape'&&!busy&&!action)setSelected(null);}}>
      <header className="v1ops-drawer-head"><div><h2>Order #{selected.slice(0,8).toUpperCase()}</h2><small>{selected}</small></div><button disabled={busy} onClick={()=>setSelected(null)}>Close</button></header>{detailError&&<p role="alert" className="v1ops-error">{detailError}</p>}{!detail&&!detailError&&<p>Opening order details...</p>}{!detail&&detailError&&<button onClick={()=>void loadDetail().catch(e=>setDetailError(e.message))}>Retry order details</button>}
      {detail&&<><section className="v1ops-card"><Badge value={cancellation&&!['COMPLETED','REJECTED'].includes(cancellation.status)?'CANCELLATION REQUESTED':detail.status}/><Entry name="Customer">{detail.customer_name}</Entry><p>{detail.customer_email} · {detail.customer_mobile}</p><p>{Object.values(detail.shipping_address||{}).filter(Boolean).join(', ')}</p><Entry name="Payment">{detail.payment_method} · {label(detail.payment_status)}</Entry><Entry name="Products">{cash(detail.totals?.subtotal)}</Entry><Entry name="Delivery">{cash(detail.totals?.delivery_fee??detail.totals?.shipping)}</Entry><Entry name="COD fee">{cash(detail.totals?.cod_fee)}</Entry><Entry name="Rewards redeemed">{detail.totals?.reward_points||0} points</Entry><Entry name="Original order total">{cash(detail.total)}</Entry>{detail.items.map(item=><div className="v1ops-item" key={item.id}>{item.image_url&&<img src={item.image_url} alt=""/>}<div><strong>{item.product_name||'Clothing'}</strong><p>{item.size} · {item.colour} · {item.qty} × {cash(item.price)}</p></div></div>)}</section>
      <section className="v1ops-card"><h3>Cancellation</h3>{cancellation?<><Badge value={cancellation.status}/><p>{cancellation.reason}</p><small>{when(cancellation.created_at)} · {cancellation.source}</small>{cancellation.last_error&&<p className="v1ops-error">{cancellation.last_error}</p>}<Entry name="Refund">{cash(Number(cancellation.refund_amount_paise)/100)} · {label(cancellation.refund_status)}</Entry><Entry name="Reward points to restore">{cancellation.refund_points}</Entry><div className="v1ops-actions">{['REQUESTED','REVIEW_REQUIRED'].includes(cancellation.status)&&<><button disabled={busy} onClick={()=>void run(`/storefront/admin/cancellations/${selected}/process`,{},'Cancellation check finished.')}>Verify & process cancellation</button>{!cancellation.carrier_attempted&&<button disabled={busy} onClick={()=>setAction({type:'rejectCancellation',title:'Reject cancellation request',description:'The recorded reason will be visible to the customer.'})}>Reject with reason</button>}</>}{cancellation.status==='COMPLETED'&&cancellation.refund_status==='PENDING_REFUND'&&<button disabled={busy} onClick={()=>refund('CANCELLATION',cancellation)}>Process product refund</button>}</div></>:<><p>No cancellation request recorded.</p><button disabled={busy||/CANCEL|DELIVER|SHIPPED|RTO|RETURN/.test(detail.status)} onClick={()=>setAction({type:'cancel',title:'Cancel this order',description:'The backend will verify cancellation eligibility, the carrier and payment before restoring stock and points.'})}>Cancel with reason</button></>}</section>
      <ShippingControls id={selected} onChanged={loadDetail}/>
      <section className="v1ops-card"><h3>Returns & inspection</h3>{!detail.returns.length&&<p>No return requests.</p>}{detail.returns.map(request=><article key={request.id} className="v1ops-return"><strong>Return #{request.id} · {request.type}</strong><Badge value={request.status}/><p>{request.reason}</p>{request.notes&&<small>{request.notes}</small>}<p>Items: {(request.items||[]).map(i=>`${i.sale_item_id||i.variant_id} (qty ${i.qty})`).join(', ')}</p><Entry name="Product refund">{request.refund_amount_paise!=null?cash(Number(request.refund_amount_paise)/100):'Invoice review required'}</Entry><Entry name="Points to restore">{request.refund_points||0}</Entry><Entry name="Refund status">{label(request.refund_status)}</Entry>{request.bank_upi&&<p>Customer UPI: {request.bank_upi}</p>}{request.items_received_at&&<p>Inspected {when(request.items_received_at)} · {request.inventory_restocked_at?'Stock restored':'Not restored to sellable stock'}</p>}{request.reverse_pickup_error&&<p className="v1ops-error">{request.reverse_pickup_error}</p>}{request.reverse_shipment&&<p>Reverse shipment: {request.reverse_shipment.awb||request.reverse_shipment.shiprocket_shipment_id||'Booked'} · {request.reverse_shipment.status}</p>}<ReverseControls request={request} onChanged={loadDetail}/><div className="v1ops-actions">{request.status==='REQUESTED'&&<><button disabled={busy} onClick={()=>setAction({type:'approveReturn',id:request.id,title:'Approve return & book reverse order',description:'This books a reverse order in Shiprocket. Choose its courier, generate the return AWB and request pickup next. Refund after receiving and inspecting the items.'})}>Approve & book return</button><button disabled={busy||request.reverse_pickup_attempted} onClick={()=>setAction({type:'rejectReturn',id:request.id,title:'Reject return',description:'Record the reason for the customer.'})}>Reject</button></>}{request.status==='APPROVED'&&!request.items_received_at&&<button disabled={busy} onClick={()=>setAction({type:'receive',id:request.id,title:'Receive & inspect return',description:'Confirm the selected returned items have arrived. Choose whether they are sellable.'})}>Receive & inspect</button>}{request.items_received_at&&request.refund_status!=='REFUNDED'&&request.type!=='REPLACE'&&<button disabled={busy} onClick={()=>refund('RETURN',request)}>Process product refund</button>}</div></article>)}</section>
      <section className="v1ops-card"><h3>Refund provider status</h3>{!detail.refund_operations.length&&<p>No gateway refund initiated.</p>}{detail.refund_operations.map(operation=><div className="v1ops-return" key={operation.id}><Badge value={operation.status}/><Entry name={operation.kind}>{cash(operation.amount)}</Entry><p>{operation.reference||'Reference awaiting confirmation'}</p>{operation.last_error&&<p className="v1ops-error">{operation.last_error}</p>}{operation.provider==='RAZORPAY'&&operation.status!=='PROCESSED'&&<button disabled={busy} onClick={()=>{void run(`/order-management/refunds/${operation.kind}/${operation.request_id}/reconcile`,{},'Refund status checked.');}}>Check provider status</button>}</div>)}</section>
      <section className="v1ops-card"><h3>Reward points audit</h3>{!detail.reward_history.length&&<p>No points used on this order.</p>}{detail.reward_history.map((entry,index)=><Entry key={index} name={`${label(entry.transaction_type)} · ${when(entry.created_at)}`}>{entry.points} points</Entry>)}</section>
      <section className="v1ops-card"><h3>Order timeline</h3><ol className="v1ops-timeline">{detail.timeline.map(event=><li key={event.id}><strong>{label(event.event_type)} · {label(event.status)}</strong><small>{when(event.occurred_at)}{event.details?.historical?' (original record)':''}</small>{event.details?.reason&&<p>{event.details.reason}</p>}{event.details?.carrier_status&&<p>{event.details.carrier_status}</p>}{event.details?.refund_status&&<p>Refund: {label(event.details.refund_status)}</p>}</li>)}</ol></section></>}
    </section></div>}
    {action&&<ActionDialog key={`${action.type}-${action.id||selected}`} action={action} busy={busy} onClose={()=>{if(!busy)setAction(null);}} onSubmit={submit}/>}
  </main>;
}
